services:
  aspnet_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Change to Production as needed
      - ASPNETCORE_URLS=http://+:5171
    ports:
      - "5171:5171"  # Change to your preferred port -> host_port:container_port
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
