// <auto-generated />
using GirafAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GirafAPI.Data.Migrations
{
    [DbContext(typeof(GirafDbContext))]
    [Migration("20241001151341_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GirafAPI.Entities.Resources.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekplanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeekplanId");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("GirafAPI.Entities.Weekplans.Weekplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Weekplans");
                });

            modelBuilder.Entity("GirafAPI.Entities.Resources.Citizen", b =>
                {
                    b.HasOne("GirafAPI.Entities.Weekplans.Weekplan", "Weekplan")
                        .WithMany()
                        .HasForeignKey("WeekplanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weekplan");
                });
#pragma warning restore 612, 618
        }
    }
}
